# This is a basic workflow to help you get started with Actions

name: CI
run-name: Run by ${{ github.actor }}


env:
  GITHUB_ACTIONS: SomeAction
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job was triggered by event ${{ github.event_name }}"
      - run: echo "Name of the branch is ${{ github.ref }} and your repository ${{ github.repository }}"
      - run: echo "${{ env.GITHUB_ACTIONS }}"



